# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-22 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_profile_codeforces_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='codeforces_name',
        ),
    ]
